### PR TITLE
#16 Adding secret_key_base for secrets.yml file

### PR DESCRIPTION
**Pull request by Sontsevolosa**
* Adding secret.yml.example as template for config/secrets.yml

secret_token is not needed.

### CODE REVIEW

**Comment by Sontsevolosa** [comment]
@mluts please, review my code

**Comment by mluts** [comment]
@Sontsevolosa Please fix the CI

**Comment by Sontsevolosa** [comment]
@mluts I did it - tests in CircleCI are green 💪☺

**Comment by mluts** [comment]
@Sontsevolosa Good 👍

**Comment by Sontsevolosa** [comment]
@mluts can I make merge?

**Comment by mluts** [comment]
@Sontsevolosa sure

**Pull request merged**
